language: node_js
node_js:
  - "5"
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "labs.cyarie.com"
  endpoint: "labs.cyarie.com.s3-website-us-east-1.amazonaws.com"
  region: us-east-1
  skip_cleanup: true
  upload_dir: "/cyarie-react"
  acl: public_read
  local-dir: dist
  detect_encoding: true